### PR TITLE
Visualisation editor page

### LINKED ISSUE #69: Implement functionality for actually adding data source + visualisation to dashboard
### Description
Implement the actual functionality (updating global state) that adds the data source + visualisation.

### Subtasks
- [ ] Make the add data source / select visualisation pages functional

### LINKED ISSUE #74: Docker doesn't respect modern TypeScript
### Description
Our Docker configuration doesn't seem to like non-null assertions, generic components and several other modern TypeScript features. It should support this.

### Steps to reproduce
1. Push a commit to a remote branch (in this repo) using either generic functional components, non-null assertion, or `as` casting.
2. Take a look at docker build logs

Example: https://github.com/IT2901-SINTEF01/frontend/pull/72/checks?check_run_id=2148614277#step:8:171

### Expected behaviour
No errors.

### Details
Deduce from docker builds and Github Actions files.

### PR DESCRIPTION
**Pull request by emilom**
Created organism for visualisation editor page. This page includes a molecule for previewing the visualisation and selecting different parameters like size and description. The page is routed from the DataExplorer organism. App.tsx is changed to include this routing. 

closes #69 nice 🙈
closes #74

### CODE REVIEW

File: src/components/atoms/AddToDashboard.tsx [hunk 1]
```diff
@@ -0,0 +1,38 @@
+import React, { useEffect, useState } from 'react';
+import { Button, CrossIcon, PlusIcon } from 'evergreen-ui';
+import { dashboardItemsVar } from '../../cache';
+import { DashboardItemInfo } from '../../types/dashboard';
+import { useReactiveVar } from '@apollo/client';
+
+const AddToDashboard: React.FC<DashboardItemInfo> = ({ size, paragraph, query, id, title }) => {
+    const dashboardItems = useReactiveVar(dashboardItemsVar);
+    const [added, setAdded] = useState<boolean>(false);
```
Comment (FredrikAugust) [inline src/components/atoms/AddToDashboard.tsx]:
```suggestion
    const [added, setAdded] = useState(false);
```

File: src/components/atoms/AddToDashboard.tsx [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+        setAdded(dashboardItems.some((el) => el.id === id));
+    }, [dashboardItems]);
+
+    const addDashboardItem = () => {
+        dashboardItemsVar([...dashboardItemsVar(), { size, query, paragraph, id, title }]);
+    };
+
+    const removeDashboardItem = () => {
+        dashboardItemsVar(dashboardItemsVar().filter((el) => el.id !== id));
+    };
```
Comment (FredrikAugust) [inline src/components/atoms/AddToDashboard.tsx]: Move business logic to molecule.

File: src/components/atoms/AddToDashboard.tsx [hunk 3]
```diff
@@ -0,0 +1,38 @@
...
+import { DashboardItemInfo } from '../../types/dashboard';
+import { useReactiveVar } from '@apollo/client';
+
+const AddToDashboard: React.FC<DashboardItemInfo> = ({ size, paragraph, query, id, title }) => {
+    const dashboardItems = useReactiveVar(dashboardItemsVar);
+    const [added, setAdded] = useState<boolean>(false);
+
+    useEffect(() => {
+        setAdded(dashboardItems.some((el) => el.id === id));
+    }, [dashboardItems]);
```
Comment (FredrikAugust) [inline src/components/atoms/AddToDashboard.tsx]: Ref. comment under.

File: src/components/atoms/VisualisationParameterSelector.tsx [hunk 4]
```diff
@@ -0,0 +1,60 @@
...
+import { Pane, SelectField, Switch, Textarea } from 'evergreen-ui';
+import { DashboardItemSize } from '../../types/dashboard';
+
+type VisualisationParameterSelectorProps = {
+    setSize: (size: DashboardItemSize) => void;
+    setParagraph: (text: string | undefined) => void;
+};
+
+const VisualisationParameterSelector: React.FC<VisualisationParameterSelectorProps> = ({ setSize, setParagraph }) => {
+    const [withText, setWithText] = useState<boolean>(false);
```
Comment (FredrikAugust) [inline src/components/atoms/VisualisationParameterSelector.tsx:11]:
```suggestion
    const [withText, setWithText] = useState(false);
```

File: src/components/atoms/VisualisationParameterSelector.tsx [hunk 5]
```diff
@@ -0,0 +1,60 @@
+import React, { useState } from 'react';
+import { Pane, SelectField, Switch, Textarea } from 'evergreen-ui';
+import { DashboardItemSize } from '../../types/dashboard';
+
+type VisualisationParameterSelectorProps = {
+    setSize: (size: DashboardItemSize) => void;
+    setParagraph: (text: string | undefined) => void;
+};
+
+const VisualisationParameterSelector: React.FC<VisualisationParameterSelectorProps> = ({ setSize, setParagraph }) => {
```
Comment (FredrikAugust) [inline src/components/atoms/VisualisationParameterSelector.tsx:10]: Molecule

File: src/components/atoms/VisualisationParameterSelector.tsx [hunk 6]
```diff
@@ -0,0 +1,60 @@
...
+            case 'small':
+                setSize(DashboardItemSize.SMALL);
+                break;
+            case 'medium':
+                setSize(DashboardItemSize.MEDIUM);
+                break;
+            case 'large':
+                setSize(DashboardItemSize.LARGE);
+        }
+    };
```
Comment (FredrikAugust) [inline src/components/atoms/VisualisationParameterSelector.tsx]: Use `enum` and cast

File: src/components/molecules/VisualisationPreview.tsx [hunk 7]
```diff
@@ -0,0 +1,61 @@
...
+import VisualisationParameterSelector from '../atoms/VisualisationParameterSelector';
+import AddToDashboard from '../atoms/AddToDashboard';
+import { WEATHER_MET_API } from '../../queries/metApi';
+
+type VisualisationPrevewProps = {
+    metadata: MetadataEntry;
+};
+
+const VisualisationPrevew: React.FC<VisualisationPrevewProps> = ({ metadata }) => {
+    const [paragraph, setParagraph] = useState<string | undefined>();
```
Comment (FredrikAugust) [inline src/components/molecules/VisualisationPreview.tsx]:
```suggestion
    const [paragraph, setParagraph] = useState<string>();
```

File: src/components/molecules/VisualisationPreview.tsx [hunk 8]
```diff
@@ -0,0 +1,61 @@
...
+    const [size, setSize] = useState<DashboardItemSize>(DashboardItemSize.LARGE);
```
Comment (FredrikAugust) [inline src/components/molecules/VisualisationPreview.tsx:17]:
```suggestion
    const [size, setSize] = useState(DashboardItemSize.LARGE);
```

not sure

File: src/components/organisms/DataExplorer.tsx [hunk 9]
```diff
@@ -40,12 +41,14 @@ const DataExplorer: React.FC = () => {
         <Pane>
             {data.allMetadata.map((el) => (
                 <Pane margin="2rem" key={el.id}>
-                    <DataResultItem
-                        title={el.name}
-                        description={el.description}
-                        tags={el.tags}
-                        visualisationType={el.visualisations[0].type}
-                    />
+                    <Link to={`/explore/edit/${el.id}`} style={{ textDecoration: 'none' }}>
```
Comment (FredrikAugust) [inline src/components/organisms/DataExplorer.tsx]: Global override with css:

```css
a {
  text-decoration: none;
}
```

**Review by FredrikAugust — CHANGES_REQUESTED** [review]

**Review by FredrikAugust — DISMISSED** [review]

**Comment by FredrikAugust** [comment]
loogietoomie

**Review by FredrikAugust — APPROVED** [review]
